# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Sync Douban to Notion

on:
  workflow_dispatch: # manual trigger
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 */1 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: notion-transfer-deploy

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
    - name: Sync Douban to Notion
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        BASE_PAGE_ID: ${{ secrets.BASE_PAGE_ID }}
        BOOK_DATABASE_ID: ${{ secrets.BOOK_DATABASE_ID }}
        MOVIE_DATABASE_ID: ${{ secrets.MOVIE_DATABASE_ID }}
        DOUBAN_COOKIE: ${{ secrets.DOUBAN_COOKIE }}
        DOUBAN_CK: ${{ secrets.DOUBAN_CK }}
        UID: ${{ secrets.UID }}
        USER_AGENT: ${{ vars.USER_AGENT }}
      run: |
        # perform sync operation
        python sync_douban.py --sync
